### ISSUE TITLE
python3/pip3 not working

### ISSUE THREAD

**Issue by fluffy-critter** [hashbang/hashbang#34]
Hi, I just signed up for a shell account on sf1.hashbang.sh and I'm having trouble trying to install any user packages with `pip3` (however, Python 2's `pip` is working fine).

For example, `pip3 install --user pipenv` results in:

```
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pip/_vendor/__init__.py", line 33, in vendored
    __import__(vendored_name, globals(), locals(), level=0)
ImportError: No module named 'pip._vendor.pkg_resources'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/pip3", line 9, in <module>
    from pip import main
  File "/usr/lib/python3/dist-packages/pip/__init__.py", line 21, in <module>
    from pip._vendor.requests.packages.urllib3.exceptions import DependencyWarning
  File "/usr/lib/python3/dist-packages/pip/_vendor/__init__.py", line 76, in <module>
    vendored("pkg_resources")
  File "/usr/lib/python3/dist-packages/pip/_vendor/__init__.py", line 36, in vendored
    __import__(modulename, globals(), locals(), level=0)
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 634, in _load_backward_compatible
  File "/usr/share/python-wheels/pkg_resources-0.0.0-py2.py3-none-any.whl/pkg_resources/__init__.py", line 3019, in <module>
  File "/usr/share/python-wheels/pkg_resources-0.0.0-py2.py3-none-any.whl/pkg_resources/__init__.py", line 3003, in _call_aside
  File "/usr/share/python-wheels/pkg_resources-0.0.0-py2.py3-none-any.whl/pkg_resources/__init__.py", line 3032, in _initialize_master_working_set
  File "/usr/share/python-wheels/pkg_resources-0.0.0-py2.py3-none-any.whl/pkg_resources/__init__.py", line 646, in _build_master
  File "/usr/share/python-wheels/pkg_resources-0.0.0-py2.py3-none-any.whl/pkg_resources/__init__.py", line 639, in __init__
  File "/usr/share/python-wheels/pkg_resources-0.0.0-py2.py3-none-any.whl/pkg_resources/__init__.py", line 695, in add_entry
  File "/usr/share/python-wheels/pkg_resources-0.0.0-py2.py3-none-any.whl/pkg_resources/__init__.py", line 2012, in find_on_path
```

and while I'm able to install it with Python2 pip, running `pipenv --three` (to force it to use python3) results in:

```
Traceback (most recent call last):
  File "/home/hokkori/.local/bin/pipenv", line 11, in <module>
    sys.exit(cli())
  File "/home/hokkori/.dotfiles/git/.local/lib/python2.7/site-packages/pipenv/vendor/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/hokkori/.dotfiles/git/.local/lib/python2.7/site-packages/pipenv/vendor/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/hokkori/.dotfiles/git/.local/lib/python2.7/site-packages/pipenv/vendor/click/core.py", line 1114, in invoke
    return Command.invoke(self, ctx)
  File "/home/hokkori/.dotfiles/git/.local/lib/python2.7/site-packages/pipenv/vendor/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/hokkori/.dotfiles/git/.local/lib/python2.7/site-packages/pipenv/vendor/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/hokkori/.dotfiles/git/.local/lib/python2.7/site-packages/pipenv/vendor/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/home/hokkori/.dotfiles/git/.local/lib/python2.7/site-packages/pipenv/vendor/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/hokkori/.dotfiles/git/.local/lib/python2.7/site-packages/pipenv/vendor/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/hokkori/.local/lib/python2.7/site-packages/pipenv/cli/command.py", line 208, in cli
    clear=state.clear,
  File "/home/hokkori/.local/lib/python2.7/site-packages/pipenv/core.py", line 574, in ensure_project
    pypi_mirror=pypi_mirror,
  File "/home/hokkori/.local/lib/python2.7/site-packages/pipenv/core.py", line 516, in ensure_virtualenv
    ensure_python(three=three, python=python)
  File "/home/hokkori/.local/lib/python2.7/site-packages/pipenv/core.py", line 397, in ensure_python
    path_to_python = find_a_system_python(python)
  File "/home/hokkori/.local/lib/python2.7/site-packages/pipenv/core.py", line 360, in find_a_system_python
    python_entry = finder.find_python_version(line)
  File "/home/hokkori/.local/lib/python2.7/site-packages/pipenv/vendor/backports/functools_lru_cache.py", line 137, in wrapper
    result = user_function(*args, **kwds)
  File "/home/hokkori/.local/lib/python2.7/site-packages/pipenv/vendor/pythonfinder/pythonfinder.py", line 114, in find_python_version
    major=major, minor=minor, patch=patch, pre=pre, dev=dev, arch=arch, name=name
  File "/home/hokkori/.local/lib/python2.7/site-packages/pipenv/vendor/pythonfinder/models/path.py", line 396, in find_python_version
    ver = next(iter(self.get_pythons(sub_finder)), None)
  File "/home/hokkori/.local/lib/python2.7/site-packages/pipenv/vendor/pythonfinder/models/path.py", line 279, in get_pythons
    reverse=True
  File "/home/hokkori/.local/lib/python2.7/site-packages/pipenv/vendor/pythonfinder/models/path.py", line 277, in <genexpr>
    (p for p in self._filter_paths(finder) if p.is_python),
  File "/home/hokkori/.local/lib/python2.7/site-packages/pipenv/vendor/pythonfinder/models/path.py", line 264, in <genexpr>
    pth for pth in unnest(finder(p) for p in self.path_entries if p is not None)
  File "/home/hokkori/.local/lib/python2.7/site-packages/pipenv/vendor/pythonfinder/utils.py", line 251, in unnest
    for el in target:
  File "/home/hokkori/.local/lib/python2.7/site-packages/pipenv/vendor/pythonfinder/models/path.py", line 264, in <genexpr>
    pth for pth in unnest(finder(p) for p in self.path_entries if p is not None)
  File "/home/hokkori/.local/lib/python2.7/site-packages/pipenv/vendor/pythonfinder/models/mixins.py", line 121, in find_python_version
    for child in unnest(self.pythons.values())
  File "/home/hokkori/.local/lib/python2.7/site-packages/pipenv/vendor/pythonfinder/models/path.py", line 531, in pythons
    for path, entry in self.children.items():
  File "/home/hokkori/.dotfiles/git/.local/lib/python2.7/site-packages/pipenv/vendor/cached_property.py", line 35, in __get__
    value = obj.__dict__[self.func.__name__] = self.func(obj)
  File "/home/hokkori/.local/lib/python2.7/site-packages/pipenv/vendor/pythonfinder/models/path.py", line 501, in children
    for child_key, child_val in self._gen_children():
  File "/home/hokkori/.local/lib/python2.7/site-packages/pipenv/vendor/pythonfinder/models/path.py", line 484, in _gen_children
    for child in self._filter_children():
  File "/home/hokkori/.dotfiles/git/.local/lib/python2.7/site-packages/pipenv/vendor/pathlib2/__init__.py", line 1279, in iterdir
    for name in self._accessor.listdir(self):
  File "/home/hokkori/.dotfiles/git/.local/lib/python2.7/site-packages/pipenv/vendor/pathlib2/__init__.py", line 541, in wrapped
    return strfunc(str(pathobj), *args)
OSError: [Errno 13] Permission denied: '/usr/local/bin'
```

It seems weird that /usr/local/bin and /usr/local/lib would be permission-denied, and also that the python3 installation would rely on those.

**Comment by Arnie97** [comment]
The path `/usr/local/lib/python2.7` is not readable, so `pip2` just skips it.

```
$ ls -l /usr/local/lib
total 12
drwxr-sr-x. 3 root staff 4096 Jan  2  2016 luarocks/
drwxr-s---  4 root staff 4096 Oct 31  2018 python2.7/
drwxrwsr-x  3 root staff 4096 Jul 18  2018 python3.5/
```

On the other hand, `/usr/local/lib/python3.5` is readable by everyone; however the permissions of directories in `/usr/local/lib/python3.5/dist-packages` are `drwx--S---`, and this breaks `pip3`.

```
$ ls -l /usr/local/lib/python3.5/dist-packages
total 896
drwx--S--- 18 root staff   4096 Jul 18  2018 ansible/
drwx--S---  2 root staff   4096 Jul 18  2018 ansible-2.6.1.dist-info/
...
drwx--S---  2 root staff   4096 Jul 18  2018 PyYAML-3.13.dist-info/
drwx--S---  3 root staff   4096 Jul 18  2018 yaml/
```

**Comment by Arnie97** [comment]
Before the permissions are fixed, I've found some hacky workarounds to make `pip3` work:

## Method A
Patch the `pkg_resources` package. This would be quite straight-forward: just follow the error message and remove the check:
```diff
--- a/.local/lib/python3.5/site-packages/pip/_vendor/pkg_resources/__init__.py
+++ b/.local/lib/python3.5/site-packages/pip/_vendor/pkg_resources/__init__.py
@@ -2115,9 +2115,6 @@
 def distributions_from_metadata(path):
     root = os.path.dirname(path)
     if os.path.isdir(path):
-        if len(os.listdir(path)) == 0:
-            # empty metadata dir; skip
-            return
         metadata = PathMetadata(root, path)
     else:
         metadata = FileMetadata(path)
```

If you were not sure how to manually install pip to `~/.local` without a working pip, you might bootstrap with my patched version:

`$ cd ~ && tar -kxzvf` [patched_pip_19.2.3.tar.gz](https://github.com/hashbang/hashbang/files/3569392/patched_pip_19.2.3.tar.gz)

## Method B
Downgrade to `pip==8.1.2`.

**Comment by Arnie97** [comment]
To the sysops:

`$ sudo chmod o-rwx /usr/local/lib/python3.5` should fix `pip3`.

**Comment by RyanSquared** [comment]
This should be resolved once we migrate to new, clean hosts within the next month or so.
